name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 16.x ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm i

      - name: Prepare
        run: npm run dev-prepare

      - name: Lint
        run: npm run lint

      #- name: Test
      #  run: npm run test:coverage

      - name: Build
        run: npm run prepack

      - name: Release
        run: npm publish -q --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
